### PR TITLE
WIP: fix(interface): add missing keys in Theme

### PR DESCRIPTION
**Pull request by RaphaelGimenez**
- Added missing keys to match tailwind's doc https://tailwindcss.com/docs/theme#configuration-reference
- Rearranged keys to match https://tailwindcss.com/docs/theme#configuration-reference

### CODE REVIEW

**Comment by RaphaelGimenez** [comment]
Hi, even when removing all defaults values that I added in previous commit I get 12.56 KB gzipped twind.js. Should the limit be increased in this case ?

**Comment by sastan** [comment]
Thanks for the PR. Most of the config values that you have added are automatically inferred by Twind (for example https://github.com/tw-in-js/twind/blob/main/src/__tests__/api.json#L167) and do not need to be present in the theme config. 
Did you have a utility that is not working?

**Comment by RaphaelGimenez** [comment]
Oh ok, I had an error using Twind with NextJs typescript.

```javascript
import { setup } from "twind";
import twindConfig from "../twind.config";
setup({ ...twindConfig, sheet });
/// twind.config
module.exports = {
  theme: {
    extend: {
      flexGrow: { 2: 2 },
    },
  },
};
```
was giving me the error :
```
Type '{ flexGrow: { 2: number; }; }' is not assignable to type 'Partial<Theme>'.
Object literal may only specify known properties, and 'flexGrow' does not exist in type 'Partial<Theme>'
```

So I thought I should add missing keys in the interface.

**Comment by sastan** [comment]
I see. `flex-grow-2`works without having it in the theme. But there may be cases for some of the sections you mentioned to have custom theme values like `flex-grow-large` -> `flex-grow: 3` – I do not know if that is a real use case?

**Comment by RaphaelGimenez** [comment]
Yeah mb, I just coppied my tailwind conf 😅 It works fine without the `flex-grow-2`. But still, shouldn't the theme interface implement all tailwinds `Core Plugin`? 💁‍♂️

**Comment by sastan** [comment]
You are right. I'm currently using your PR as a base to introduce the missing types. The corresponding plugins need to be updated as well – otherwise, the theme values would be of no use. I'm working on that right now.

**Comment by sastan** [comment]
Could you please try the new 0.16.0 release?

**Comment by RaphaelGimenez** [comment]
Working fine :)

**Pull request closed without merging**
