### PR TITLE
refactor: use stylis as prefixer

### PR DESCRIPTION
**Pull request by SukkaW**
The PR supersedes #311 and is now targeting the `next` branch. And I also port the unit test from the `main` branch.

----

Replace `style-vendorizer` with `stylis`:

- `stylis` supports more prefixes than `style-vendorizer` (see the change of unit tests).
- `stylis` is way faster and more efficient ([here is how `stylis` implemented their prefixer](https://github.com/thysultan/stylis/blob/master/src/Prefixer.js))
- `stylis` is used by many popular CSS-in-JS libraries like [emotion](https://emotion.sh/), [linaria](https://github.com/callstack/linaria) and Vercel's [styled-jsx](https://github.com/vercel/styled-jsx)

----

The pull request is marked as a draft:

- `stylis` doesn't support prefix `tab-size` yet, https://github.com/thysultan/stylis/pull/288
- `stylis` doesn't support prefix `position:sticky !important` (however it does support `position:sticky!important`) yet, https://github.com/thysultan/stylis/pull/289

### CODE REVIEW

**Comment by sastan** [comment]
Awesome. Really like to solution. Did you notice any file size changes?

**Comment by SukkaW** [comment]
> Awesome. Really like to solution. Did you notice any file size changes?

Actually, yes. It seems that `stylis` (after tree shaking and minified) is about 500 bytes larger than `style-vendorizer` (I have run `pnpm run build` then compared the umd size).

I assume it is because stylis supports a wider range of properties and values.

**Comment by SukkaW** [comment]
`stylis@4.1.1` has been released. Mark the PR ready to review.

**Comment by sastan** [comment]
Closing for now... because I'll rename the next branch to main and this will close this PR. Please re-open if this is still issue for you. In the meantime I've update style-vendorizer. Maybe all issue are solved now.

**Pull request closed without merging**
