### PR TITLE
fix: properly handle arbitrary var names with dashed digits

### PR DESCRIPTION
**Pull request by sibbng**
For some reason `w-[calc(100%/3-1rem*2)]` test fails.

But when I run that on browser console it gives me expected result.
`"w-[calc(100%/3-1rem*2)]".replace(/(-?\d*\.?\d(?!\b-.+[,)](?![^+\-/*]))(?:%|[a-z]+)?|\))([+\-/*])/g, '$1 $2 ')`

I really would like to learn why it fails.

### CODE REVIEW

**Comment by sastan** [comment]
I do not know. I tried a different regexp (`(var\(--[^)]+?\)|-?\d*\.?\d(?:%|[a-z]+)?|\))([+\-/*])`)  but than the test for var with calc fallback fails. 

As I understand these tests: they are for variables that start with `--<number>`. Is this really an issue?

**Comment by sibbng** [comment]
> As I understand these tests: they are for variables that start with `--<number>`. Is this really an issue?

Yes

**Comment by sibbng** [comment]
> > As I understand these tests: they are for variables that start with `--<number>`. Is this really an issue?
> 
> Yes

To clarify actual issue is `--<number>-<number>`

**Comment by sibbng** [comment]
@sastan I fixed the issue on latest commit.

At first try I wasn't aware of that square brackets are getting removed in `handleArbitraryValues`. My regex were only working if that `key` wrapped with **square brackets**. Actually at least one more character at the end of string was fix that regex.

`calc(100%/3-1rem*2)` => calc(100% / 3-1rem * 2)] ❌
`calc(100%/3-1rem*2)]` => calc(100% / 3 - 1rem * 2)] ✅

Anyway I fixed issue by modifying the regex slightly. Probably it could be more simplified.

Looks like CI failing because of size limits right now.

**Comment by sastan** [comment]
Great! Awesome job.

**Comment by sastan** [comment]
Regarding the failed size report could you increase the size limit to 12.1 and then we can get this merged.

**Comment by sibbng** [comment]
> Great! Awesome job.

Thanks 🤗

> Regarding the failed size report could you increase the size limit to 12.1 and then we can get this merged.

Done 👍

**Comment by sastan** [comment]
I'll create a release soon within the next day.

**Comment by sastan** [comment]
There you go: v0.16.12

**Pull request merged**
