### PR TITLE
Docs Site: Prepare for publish

### PR DESCRIPTION
**Pull request by gojutin**
This PR is a replacement to #124 and includes all changes included in that PR. It is also rebased to the the `main` branch. 

The docs site is still a work in progress, and will continue to be refined with the help of community feedback. Publishing the docs site will also allow us to begin the Algolia integration process.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Hey @gojutin thanks for your patience here. It's been a bit of a hectic month so far for me. I have looked and and read through the preview deploy here. Everything look great.

Do you see any reason why we shouldn't merge this now? Do we need to do anything to make it deploy to a certain URL?

**Comment by sastan** [comment]
@lukejacksonn I can take care of deployment

**Comment by lukejacksonn** [comment]
Ok then I say we merge this for now and use it as a basis for V1 docs going forward.

**Comment by sastan** [comment]
@lukejacksonn Working on the website publish.

**Pull request merged**
