### PR TITLE
feat: support arbitrary values using square bracket notation

### PR DESCRIPTION
**Pull request by sastan**
This PR adds the new tailwindcss square bracket notation like `top-[-113px]`. Works with variants too, like `md:top-[-113px]`.

This works in places where a theme value would be used. So almost everywhere.

I would like to add a config option to disable this feature. But I'm unsure of the name. Any pointers?

Which one do you prefer: arbitraryValues or dynamicValues?

---

Here are some examples: _Not everyone works right now – working on colors vs other value_

```
bg-[#0f0]
bg-[#ff0000]
bg-[#0000ffcc]
bg-[hsl(0,100%,50%)]
bg-[hsla(0,100%,50%,0.3)]
bg-[rgb(123,123,123)]
bg-[rgba(123,123,123,var(--tw-bg-opacity))]
bg-opacity-[0.11]
border-[#f00]
border-[2.5px]
duration-[2s]
grid-cols-[200px,repeat(auto-fill,minmax(15%,100px)),300px]
grid-cols-[minmax(100px,max-content)repeat(auto-fill,200px)20%]
grid-cols-[repeat(auto-fit,minmax(150px,1fr))]
flex-[30%]
ring-[#1da1f2]
ring-[7px]
ring-offset-[#1da1f2]
ring-offset-[7px]
rotate-[0.5turn]
rotate-[23deg] rotate-[2.3rad] rotate-[401grad] rotate-[1.5turn]
rounded-[33%]
scale-[2]
scale-x-[1.15]
skew-[30deg]
skew-x-[1.07rad]
space-x-[20cm]
space-x-[calc(20%-1cm)]
text-[#1da1f2]
text-[2.23rem]
text-[6px]
text-[calc(1vw+1vh+.5vmin)]
top-[-123px]
top-[123px]
transition-[font-size,color,width]
translate-[3in]
translate-y-[2px]
w-[3.23rem]
w-[calc(100%+1rem)]
w-[clamp(23ch,50%,46ch)]
```

/cc @tw-in-js/contributors

### CODE REVIEW

**Comment by lukejacksonn** [comment]
This is awesome, I'm surprised by what small changes were required to support this feature. Personally I have concerns over the pattern generally (in the sense that it undermines the whole _design tokens_ philosophy) but that aside, we should probably support it for feature parity with Tailwind at least. It might end up being more useful in practice than I think. Really great job.

Regards the enabling/disabling.. do you see any down sides of having it enabled by default? Maybe this could/should fall under the `mode: 'strict'` policy?

**Comment by sastan** [comment]
Should be enabled by default in my opinion. But we can not use `mode` for that. We need another name.

**Comment by lukejacksonn** [comment]
Maybe something like `dynamicValues: true | false`?

**Comment by danestves** [comment]
Hi! I just want to comment that, this:

image

Is working as expected 🎉🎉🎉

image

--

But this: 

image

It's not working 🥺, it's giving an empty class at the end:

image

**Comment by danestves** [comment]
Also `text-[6px]` it's working on `@tailwindcss/jit` as you can see here https://codesandbox.io/s/elated-banach-mrrh0?file=/pages/index.js

image

Any configuration that you should do to make this work on this side?

image

**Comment by hastebrot** [comment]
> I can't recall what Tailwind referred to this feature as. I guess keeping nomenclature aligned would be beneficial.

The README in `tailwindcss-jit` calls it "square bracket notation" and "arbitrary styles".

**Comment by sastan** [comment]
> Also `text-[6px]` it's working on `@tailwindcss/jit` as you can see here https://codesandbox.io/s/elated-banach-mrrh0?file=/pages/index.js

The problem here is that `text-[...]` can be either a color or a font size value. To support this I would suggest to check if the dynamic value starts with`#` then use it as color value otherwise font size.

The same issue may affect several plugins.

**Comment by sastan** [comment]
> image
> 
> It's not working 🥺, it's giving an empty class at the end:
> 
> image

Thanks! We should support this!

**Comment by sastan** [comment]
So either `arbitraryStyles` or `dynamicValues`?

**Comment by danestves** [comment]
Do you have any estimated time when this will come out? We have a project in progress that is waiting for this feature (we already got rid of @emotion)

**Comment by sastan** [comment]
> Do you have any estimated time when this will come out? We have a project in production that is waiting for this feature (we already got rid of @emotion)

Just pushed an update with the two issues you reported. Could please you verify it works now as you expect?

I plan to publish this one and #149 on the weekend, maybe tonight...

**Comment by sastan** [comment]
> We have a project in production that is waiting for this feature (we already got rid of @emotion)

That sounds great! Could you tell us more in https://github.com/tw-in-js/twind/discussions/categories/show-and-tell?

**Comment by danestves** [comment]
@sastan 
image

I can confirm you that now is receiving the values very well!! If you update the package today it will be awesome 😍

**Comment by danestves** [comment]
I'm going to put the package into production by installing it from this PR 😂 for the excitement of all that it saves us

**Comment by sastan** [comment]
@danestves There you go twind@0.16.4

**Comment by danestves** [comment]
I will share the URL for you to see it!

**Pull request merged**
