### PR TITLE
feat: twind/shim pass options to html parser

### PR DESCRIPTION
**Pull request by tylerforesthauser**
In order to support Vue SSR and Nuxt universal apps which require matching DOM trees for hydration, we need the ability to preserve comment nodes when parsing the HTML. This PR allows for passing either a string parameter or an object literal containing an "html" property and an optional "options" property matching `node-html-parser`'s [options structure](https://github.com/taoqf/node-html-parser#parsedata-options).

```js
import { setup } from 'twind'
import { virtualSheet, shim } from 'twind/shim/server'

const sheet = virtualSheet()

setup({ ...sharedOptions, sheet })

function ssr() {
  sheet.reset()

  // Option 1: Supply an HTML string only
  const body = shim(renderTheApp())

  // Option 2: Supply an object containing the named parameters
  const body = shim({ html: renderTheApp(), options: { comment: false } })

  // ...
```

Additionally, `shim` still accepts a second argument allowing for the use of a custom `tw` instance.

```js
import { create } from 'twind'
import { virtualSheet, shim } from 'twind/shim/server'

const sheet = virtualSheet()

const { tw } create({ ...sharedOptions, sheet })

function ssr() {
  sheet.reset()

  const body = shim({ html: renderTheApp(), options: { comment: false } }, tw)

  // ...
```

### CODE REVIEW

**Review by sastan — CHANGES_REQUESTED** [review]
This looks really good. And with tests 🔥 

Maybe we can agree on a slightly different API. The shim always needs html => the first argument. All other options are _optional_. What do you think about:

```js
  const body = shim(renderTheApp())

  const body = shim(renderTheApp(), { comment: false })

  const { tw } = create()
  const body = shim(renderTheApp(), tw)
  const body = shim(renderTheApp(), { comment: false, tw })
```

Implementation stub:

```ts
interface ShimOptions extends HTMLParserOptions {
  tw?: TW
}

export const shim = (markup: string, options: TW | ShimOptions): string => {
  const { tw = defaultTW, ...parserOptions } = typeof options === 'function' ? { tw: options } : options || {}
}
```

**Comment by sastan** [comment]
One other thing. Could you add the API changes to the docs (https://github.com/tw-in-js/twind/blob/main/docs/installation.md#twindshim)?

The twind/shim section gets bigger and bigger i'm thinking about moving that to an own file (docs/shim.md) and in installation would only be a short usage and then a link to the docs.

Would you be willing to include that in this PR? Otherwise i'll do it after this is merged.

**Comment by tylerforesthauser** [comment]
Yeah that all sounds great! I agree that your way makes more sense for sure, I think I overthought that bit. I'll revise and also update docs.

**Comment by sastan** [comment]
@tylerforesthauser I have modified some files. Mainly docs. But also shim ts signature and tests to ensure grouping is expanded.

**Comment by tylerforesthauser** [comment]
Excellent, thank you! I appreciate your thoroughness. I'll try to take another pass on the docs when I can but I suspect you may get to it before I do. I hope what I've provided is at the very least a good starting point for you.

**Review by sastan — APPROVED** [review]
LGTM

**Comment by sastan** [comment]
> I'll try to take another pass on the docs when I can but I suspect you may get to it before I do.

Please do and let me know. Then we can get this merged.

> I hope what I've provided is at the very least a good starting point for you.

It helps a lot if somebody else takes a look and contributes! I just have filled in some things you couldn't know. 

Thanks a lot for you contribution! I welcome PRs very much.

**Comment by tylerforesthauser** [comment]
Ok so here's one thing I've thought of: I created the API section for `shim` but I realize that is not consistent with the client-side implementation. It probably makes the most sense to have an API section under both implementation sections, do you think?

**Comment by sastan** [comment]
> Ok so here's one thing I've thought of: I created the API section for `shim` but I realize that is not consistent with the client-side implementation. It probably makes the most sense to have an API section under both implementation sections, do you think?

Yep. Good catch. That would be awesome. The client side is:

- `setup`: like docs/setup.md maybe just a like + `target` which element should be shimmed (default to document.documentElement)
- `disconnect`: stop shimming/observing; naming comes from MutationObserver#disconnect

**Comment by sastan** [comment]
@tylerforesthauser I'll be busy with the tw.apply PR. Can you add the client API section? We could put this PR into the next release.

**Comment by tylerforesthauser** [comment]
I can certainly do that, though I wanted to ask: is the client-side `shim` function actually exported anywhere or is it simply invoked by including the module?

**Comment by sastan** [comment]
No it's only setup and disconnect. The base is the observe module (docs/observe.md and src/observe); see src/shim/index.ts

**Review by sastan — APPROVED** [review]
LGTM

**Pull request merged**
