### PR TITLE
fix: allow interpolation at grouping locations

### LINKED ISSUE #47: [UNKNOWN_THEME_VALUE] error when referencing variables in grouping using template literal syntax
This issue was originally identified in this discussion: https://github.com/tw-in-js/twind/discussions/44#discussioncomment-253093

I've included a minimal example which appears to confirm @sastan's suspicion that this issue is specific to template literal syntax. It appears to only happen when referencing outside variables.

Codesandbox Example: https://codesandbox.io/s/twind-template-literal-issue-t3zwf

### PR DESCRIPTION
**Pull request by sastan**
Resolves #47

### CODE REVIEW

**Review by gojutin — CHANGES_REQUESTED** [review]
I just tested these changes against the original Codesandbox in the reported issue. It looks like the interpolation is working on the broken example, but now failing on the syntax below. It works fine if the color is hard-coded instead of a reference. 

This works
```tsx
      <p className={tw`bg(red(200))`}>Grouping works as expected</p>
```

This breaks
```tsx
      <p className={tw`bg(${color}(200))`}>ex. 3 Grouping broken</p>
```

Error: `Uncaught Error: Error: Invalid grouping: 'bg(${...}(200))'`

**Comment by sastan** [comment]
> Error: `Uncaught Error: Error: Invalid grouping: 'bg(${...}(200))'`

This is from the previous version where i implemented fail on deopt.

Could you please check if your using `@tw-in-js/twind@0.56.19`. Either install that version explictly:

```sh
# For npm
npm install twind@npm:@tw-in-js/twind@0.56.19

# For yarn - upgrade implies install
yarn add twind@npm:@tw-in-js/twind@0.56.19
```

or make sure to use `npm install --force` or `yarn upgrade`

```sh
# For npm
npm install --force twind@npm:@tw-in-js/twind@pr56

# For yarn - upgrade implies install
yarn upgrade twind@npm:@tw-in-js/twind@pr56
```

**Comment by gojutin** [comment]
Oh, somehow I missed the giant "Try the Preview Package" section above.  I had just checked out the PR, ran a build, and referenced the local file. I might have forgotten to do a pull or something. But, I just tried again using `npm:@tw-in-js/twind@pr56` and it worked exactly as expected 👍

**Review by gojutin — APPROVED** [review]
Looks great and works as expected 👍

**Pull request merged**
