### PR TITLE
WIP: twind/styled

### PR DESCRIPTION
**Pull request by sastan**
The [styled API](https://emotion.sh/docs/styled) is commonly used within the react community. Although twind is framework agnostic it may be nice to provide a styled module as well.

The API is inspired by emotion, styled-component and goober. This PR adds three new modules:

- twind/styled - base implementation and framework agnostic
- twind/styled/react - ready to use with react
- twind/styled/preact - ready to use with preact

See [docs/styled.md](https://github.com/tw-in-js/twind/blob/twind-styled/docs/styled.md)

An example is available as [example/styled.tsx](https://github.com/tw-in-js/twind/blob/twind-styled/example/styled.tsx). After `yarn start` open http://localhost:8080/styled.html.

## Try the Preview Package

> Official releases are **only** available on [registry.npmjs.org](https://www.npmjs.com/package/twind) as `twind`.

This PR has been published to [npm.pkg.github.com](https://github.com/orgs/tw-in-js/packages?repo_name=twind) as `@tw-in-js/twind@pr7`.

**Install/Update**

<details><summary>Configure your NPM client (click to expand)</summary>

Adjust you `.npmrc` to use `https://npm.pkg.github.com` for `@tw-in-js`

```
@tw-in-js:registry=https://npm.pkg.github.com
```

Using the command line:

```sh
npm config set @tw-in-js:registry https://npm.pkg.github.com --global
```

</details>

```sh
# For npm
npm install --force twind@npm:@tw-in-js/twind@pr7

# For yarn - upgrade implies install
yarn upgrade twind@npm:@tw-in-js/twind@pr7
```

## Benchmarks

```
# Object Styles
twind: <div color="black" class="tw-3u6ba0 tw-14ssw6o"></div>
goober: <div color="black" random="0.014518000616767335" class="go3334449672" data-reactroot=""></div>
emotion: <style data-emotion="css 14zyg7u">.css-14zyg7u{display:inline-block;border-radius:3px;padding:0.5rem 0;margin:0.5rem 1rem;width:11rem;background:transparent;color:white;border:2px solid white;font-size:0.875rem;line-height:1.25rem;}.css-14zyg7u:hover{color:black;opacity:0;}.css-14zyg7u:focus{border:2px dashed black;}@media (min-width: 768px){.css-14zyg7u{font-size:1rem;line-height:1.5rem;}}@media (min-width: 1280px){.css-14zyg7u{font-size:1.125rem;line-height:1.75rem;}}</style><div color="black" class="css-14zyg7u"></div>
styled-components: <div color="black" class="sc-bdfBwQ kIZhoG"></div>
twind x 52,441 ops/sec ±0.55% (90 runs sampled)
goober@2.0.18 x 40,491 ops/sec ±0.43% (96 runs sampled)
emotion@11.0.0 x 36,848 ops/sec ±0.69% (91 runs sampled)
styled-components@5.2.1 x 38,456 ops/sec ±0.62% (90 runs sampled)

Fastest is: twind

# Template Literal Styles
twind: <div color="black" class="tw-la1urp inline-block rounded py-2 my-2 mx-4 w-44 bg-transparent text-white border-2 border-solid border-white hover:text-black hover:opacity-100 focus:border-2 focus:border-dashed focus:border-black text-sm md:text-base lg:text-lg"></div>
goober: <div color="black" random="0.44058694455997416" class="go602841230" data-reactroot=""></div>
emotion: <style data-emotion="css 1j1rmlp">.css-1j1rmlp{display:inline-block;border-radius:3px;padding:0.5rem 0;margin:0.5rem 1rem;width:11rem;background:transparent;color:white;border:2px solid white;font-size:0.875rem;line-height:1.25rem;}.css-1j1rmlp:hover{color:black;opacity:1;}.css-1j1rmlp:focus{border:2px dashed black;}@media (min-width: 768px){.css-1j1rmlp{font-size:1rem;line-height:1.5rem;}}@media (min-width: 1280px){.css-1j1rmlp{font-size:1.125rem;line-height:1.75rem;}}</style><div color="black" class="css-1j1rmlp"></div>
styled-components: <div color="black" class="sc-gsTCUz bzdKjA"></div>
twind x 57,979 ops/sec ±0.38% (93 runs sampled)
goober@2.0.18 x 43,721 ops/sec ±0.56% (96 runs sampled)
emotion@11.0.0 x 36,768 ops/sec ±0.63% (94 runs sampled)
styled-components@5.2.1 x 57,611 ops/sec ±0.45% (94 runs sampled)

Fastest is: twind
```

### CODE REVIEW

**Comment by lukejacksonn** [comment]
This is an awesome application of styled by @mattrossman - https://codesandbox.io/s/zh298

**Comment by sastan** [comment]
I have published the current state as v0.10.3-1 (tag: experimental) for anyone who wants to give this a try.

**Comment by mattrossman** [comment]
Thanks for adding the example. For reference, my main experience with css-in-js for tailwind comes from [`twin.macro`](https://github.com/ben-rogerson/twin.macro) which I think has a really ergonomic API, so that what I mentally compared this to.

Overall I like what you've done, and I was pleasantly surprised to find that it works in ways not currently specified in the `styled` documentation. For instance, you can combine different styling syntax in a list:

```js
// Passing a callback that receives props and returns list of various stylings
const Button = styled.button(({ primary }) => [
  // tagged template
  tw`font-bold`,

  // plain string
  'px-4 py-2 rounded-full',

  // prop condition (no need for ${} interpolation)
  primary ? 'bg-red-600 text-white' : 'bg-white text-gray-800',

  // CSS object notation
  css({ fontSize: '14pt' })
])
```
This is pretty close to how `twin.macro` functions, except in their case the plain string entries would be parsed as CSS by styled-components. Also, their implementation lets you use `css` as a tag function to parse regular CSS, e.g. ``` css`color: green` ```. It would  be nice to support just so people don't have to convert existing CSS to object notation.

The main issue I have with the implementation is how it behaves in VSCode. The [styled-components VSCode extension](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) expects that stuff in a ``` styled.xxx`` ``` template will be valid CSS, but since we're passing tailwind classes we end up with a bunch of linting errors:

image

By comparison, `twin.macro` has you compose tailwind components with ``` tw.xxx`` ``` and uses ``` styled.xxx`` ``` for CSS-first components (with the ability to still add tailwind styles through ``` tw`` ``` templates) so it doesn't have this problem. It's worth considering having `twind/styled` follow a similar pattern for consistency and to not cause problems with styled-components. In the sandbox shared earlier, you'll notice I inject the template functions directly into the `tw` instance.

Another linting error is thrown on the props that a callback receives:

image

This doesn't occur if you put the callback inside of a template literal like in the docs, thought it's a bit weird to write:

image


I know you're working on that Typescript plugin for intellisense which I imaging could resolve these linting issues, but I'm wondering if there's a solution for Javascript users.

**Comment by sastan** [comment]
Awesome summary. I'll need some time to dig through that. I'll get back to you tomorrow.

**Review by lukejacksonn — APPROVED** [review]
This all LGTM. The only comment I have is around the linting errors people who use styled already are going to recieve when using ``` styled.xxx`` ``` but I guess if we made ``` tw.xxx`` ``` available that might get confusing.

I don't think it's something that should prevent this from being merged but something we should think about.

**Comment by lukejacksonn** [comment]
After looking at and playing with the awesome demo in #44 I realised that it is possible to just do:

```js
import { styled as twind } from "twind/styled/react";

const Button = twind.button`...`
```

Which prevents the styled linter plugin on codesandbox from erroring. Perhaps we recommend something like this.

**Comment by sastan** [comment]
That is a good idea 💡. I'll try to look through the comment to see if wee can implement some of the other ideas.

**Comment by sastan** [comment]
We will focus our efforts on a new PR once #102 is agreed on.

**Pull request closed without merging**
