### PR TITLE
chore(NPM): package updates

### PR DESCRIPTION
**Pull request by danielweck**
Hello @sastan in my local Twind fork (branch `next`) I updated all the package dependencies.

Vitest (still in alpha) was updated too, everything works as expected.

Build + unit-test timings remain the same (ref. Discord chat):

* `time pnpm build`
* `time (pnpm test -- --no-watch && pnpm test:coverage -- --no-watch && pnpm test:ui -- --no-watch)`

### CODE REVIEW

**Comment by danielweck** [comment]
Note that this is a full lockfile refresh, including transitive dependencies (i.e. not just `pnpm update` after increasing Vitest alpha semantic versions in `package.json`, but `rm -rf node_modules && rm pnpm-lock.yaml && pnpm install`.

**Comment by danielweck** [comment]
The CI failure is:
https://github.com/tw-in-js/twind/runs/4950896130?check_suite_focus=true#step:8:217

`Error: The process '/opt/hostedtoolcache/node/16.13.2/x64/bin/npm' failed with exit code 1`

```
/usr/bin/git fetch origin next --depth=1
From https://github.com/tw-in-js/twind
 * branch            next       -> FETCH_HEAD
 * [new branch]      next       -> origin/next
/usr/bin/git checkout -f next
Previous HEAD position was 1a74959 Merge 89af187638a069892ffef3755fd07f6058451f04 into 1ed704ae782582e2751f97fec57f92ca536d6faa
Switched to a new branch 'next'
Branch 'next' set up to track remote branch 'next' from 'origin'.
/opt/hostedtoolcache/node/16.13.2/x64/bin/npm install
npm ERR! Cannot read properties of null (reading 'matches')
```

**Comment by danielweck** [comment]
The culprit is this particular GitHub Action:

https://github.com/tw-in-js/twind/blob/1ed704ae782582e2751f97fec57f92ca536d6faa/.github/workflows/ci.yml#L103-L108

**Comment by danielweck** [comment]
I fixed the CI error by *not* using the GitHub Action, but simply invoking the existing `size-limit` NPM command (just like the other `workflow` task. @sastan was there a specific reason to use `andresz1/size-limit-action` in the PR workflow?

**Comment by danielweck** [comment]
PS: I took the opportunity to upgrade PNPM from `6.27.1` to `6.28.0`. This change only affects GitHub CI (not StackBlitz or Codesandbox, etc.), and it works fine.

**Comment by sastan** [comment]
> I fixed the CI error by _not_ using the GitHub Action, but simply invoking the existing `size-limit` NPM command (just like the other `workflow` task. @sastan was there a specific reason to use `andresz1/size-limit-action` in the PR workflow?

It wanted to have the following for PRs:

- Commenting pull requests with the comparison of Size Limit output.
- Rejecting a pull request if the cost exceeds the limit.

**Comment by danielweck** [comment]
ah, makes sense :)
let's see if the CI error magically disappears this time....

**Comment by sastan** [comment]
> ah, makes sense :)
> let's see if the CI error magically disappears this time....

It will not. There is no common ancestor with the main branch 🤷🏾

**Pull request merged**
